### ISSUE TITLE
Potential Use for mapedit R package

### ISSUE THREAD

**Issue by mtreg** [16EAGLE/getSpatialData#1]
Hi - Just came across your work on getSpatialData.  Looks like a package that will have great use for lots of folks.

As I was looking through the readme, I realized this might be a great application for the [mapedit package](https://cran.r-project.org/web/packages/mapedit/index.html), in which users can interactively draw their own areas of interest and such.

Just figured I'd put the idea forth in case you weren't aware of or hadn't thought of mapedit for this. But thanks for your time on this!

**Comment by 16EAGLE** [comment]
Thank you for sharing this idea! Added the functionality to the `set_aoi` function (if called without the `aoi` argument, a `mapedit` feature drawing viewer opens). I will reference your user name in the initial version log.

**Comment by mtreg** [comment]
Great! Glad this is helpful, and thanks for the reference 👍! I love when open source works like this :-) Good luck with further development!
