### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by sippoli2** [16EAGLE/getSpatialData#12]
When I run the below code from this repository I get the following error. Any insight would be appreciated.

the error occurs when view_aoi() is run.

Error in htmlwidgets::sizingPolicy(defaultWidth = defaultWidth, defaultHeight = defaultHeight,  : 
  unused argument (browser.external = FALSE)

## Load packages
library(getSpatialData)
library(raster)
library(sf)
library(sp)

## Define an AOI (either matrix, sf or sp object)
data("aoi_data") # example aoi

aoi <- aoi_data[[3]] # AOI as matrix object, or better:
aoi <- aoi_data[[2]] # AOI as sp object, or:
aoi <- aoi_data[[1]] # AOI as sf object
#instead, you could define an AOI yourself, e.g. as simple matrix

## Define an AOI (either matrix, sf or sp object)
data("aoi_data") # example aoi

aoi <- aoi_data[[3]] # AOI as matrix object, or better:
aoi <- aoi_data[[2]] # AOI as sp object, or:
aoi <- aoi_data[[1]] # AOI as sf object
#instead, you could define an AOI yourself, e.g. as simple matrix

## set AOI for this session
set_aoi(aoi)
view_aoi() #view AOI in viewer, which will look like this:

set_aoi()

**Comment by 16EAGLE** [comment]
Thanks for reporting. I could not reproduce the error (yet). On which OS are you working and could you provide the output of `R.Version()`?

**Comment by 16EAGLE** [comment]
I could not reproduce the error on Windows. It is a problem with the `htmlwidgets` package which is not a direct dependency of `getSpatialData`. Are you using RStudio?

**Comment by 16EAGLE** [comment]
I could not reproduce the error on Windows. It is a problem with the `htmlwidgets` package which is not a direct dependency of `getSpatialData`. Are you using RStudio? Is `view_aoi` the only function that is causing this error or did you also encounter the issue with the `*_preview` functions?

**Comment by 16EAGLE** [comment]
Please let me know, if the issue still exists.

**Comment by Whjktk** [comment]
@16EAGLE Hello, I am getting the same error when I run the set_aoi() function. R version is 3.4.1 OS is windows 10
