### ISSUE TITLE
prepSentinel does not create rasters

### ISSUE THREAD

**Issue by eartherin** [16EAGLE/getSpatialData#16]
prepSentinel() produces a nested list of filenames with the specified extension (in my case, I tried both "vrt" and "tiff"), but the files in the list are nowhere to be found. Instead, the file paths in the list points to a set of text files with the same names as the filenames. Inside the text files are the names of the .jp2 that (presumably) the raster stack should be built from. I didn't think this was the intended behavior of prepSentinel(). Running R 3.5.2 and the most recent build of getSpatialData - downloaded 2 days ago from Github.

platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo

**Comment by 16EAGLE** [comment]
Sorry for the late reply, could you solve the issue? The long filenames nested inside the Sentinel zip archives caused me some trouble when testing, especially on Windows and I have not yet had time solving these issues, but will as soon as possible.

**Comment by eartherin** [comment]
The issue seemed to resolve when I used your suggestion for dealing with the long, nested filenames for Sentinel downloads. Thanks!
