### ISSUE TITLE
getLandsat_query results are shifted in longitude and do not fully match AOI

### ISSUE THREAD

**Issue by vanto1994** [16EAGLE/getSpatialData#17]
Hello, and congrats for the great package. Im having a problem when setting the extent. More specifically, I want to download time-series data of Landsat 5 and 8 for the years 1987 until 2017. The study region is Greece (path-row). Even though I am setting the extent (show them the particular code), when the download process is starting it takes scenes only from the west part of the study area (specify the path-row of the scenes). Any thoughts? Here is the code:

devtools::install_github("16EAGLE/getSpatialData")

## Load packages
library(getSpatialData)
library(raster)
library(sf)
library(sp)

#instead of using an existing AOI, you can simply draw one:
set_aoi() #call set_aoi() without argument, which opens a mapedit editor:
## set AOI for this session
view_aoi() #view AOI in viewer, which will look like this:
aoi = get_aoi(type = "sf")

## After defining a session AOI, define time range and platform
time_range <-  c("2010-01-01", "2010-02-31")

## set login credentials and archive directory
login_USGS(username = "vanto") #asks for password or define 'password'
set_archive("C:/Users/Vanto/Desktop/test")

## Use getSentinel_query to search for data (using the session AOI)
records <- getLandsat_query(time_range = time_range, aoi = aoi)

## Filter the records
colnames(records) #see all available filter attributes
unique(records$levels_available) #use one of the, e.g. to see available processing levels
unique(records$product)

records_filtered <- records[which(records$levels_available == "'source_metadata', 'l1', 'toa', 'bt', 'sr', 'sr_ndvi', 'sr_evi', 'sr_savi', 'sr_msavi', 'sr_ndmi', 'sr_nbr', 'sr_nbr2', 'stats', 'pixel_qa'"),] #filter by Level
records_filtered <- records[which(records$product == "LANDSAT_TM_C1"),] #filter by Level

records_filtered <- records_filtered[as.numeric(records_filtered$SceneCloudCover) <= 10, ] #filter by clouds

## View records table
View(records)
View(records_filtered)
#browser records or your filtered records
getLandsat_preview(record = records_filtered[6,])

**Comment by 16EAGLE** [comment]
Hello, since the code you posted is the example code from the `README`, I cannot reproduce the particular issue you are describing. Could you, for example, provide me the `AOI` that you are using for your query? In case that you draw it with `set_aoi()`, you could do
```R
aoi <- get_aoi()
save(aoi, file = "aoi.RData")
```
and upload the file created above to this thread as an attachment.

**Comment by vanto1994** [comment]
Thanks for your answer.

the problem I have is that I'm making a framework that includes Greece. The path and row of Greece is 181-186 and 31-36 and when I order my pictures it turns out way and row completely different.

Thanks

**Comment by vanto1994** [comment]
[aoi.RData.zip](https://github.com/16EAGLE/getSpatialData/files/2829658/aoi.RData.zip)

**Comment by vanto1994** [comment]
I checked the package and it works. The other problem is that it performs the same order twice. I do not know if it is normal.

Thanks!

**Comment by 16EAGLE** [comment]
Thanks, I noted the issue of double order placement and will correct it as soon as possible, see #20.
