### ISSUE TITLE
getLandsat_data "sr_ndvi" level query fails download with landsat 8 due to list error

### ISSUE THREAD

**Issue by MatthiasSiewert** [16EAGLE/getSpatialData#19]
getLandsat_data fails when sr_ndvi is requested. The order gets submitted to espa, but the function failes.
Works with "sr" level.

files <- getLandsat_data(records = query_filtered, level = "sr_ndvi", source = "auto")
Ordering requested items from ESPA...
Collecting from 1 collection(s) [olitirs8_collection], resulting in 1 order(s)...
Products 'LC08_L1TP_19....'.....01_T2' have been ordered successfully:
[level = 'sr_ndvi', format = 'gtiff', order ID(s) 'espa-xxxx@xxx.xxx-0xxxxxx-0xxxxxx-768'].
Error in xj[i] : invalid subscript type 'list'

**Comment by 16EAGLE** [comment]
Thanks for reporting, just found the source of this bug and try to solve it now.

**Comment by 16EAGLE** [comment]
Should be solved, please reinstall and let me know if it works for you.

**Comment by MatthiasSiewert** [comment]
It works now. Thanks for the effort!!!
