### ISSUE TITLE
getSentinel_query never returns more than 200 results

### ISSUE THREAD

**Issue by fpirotti** [16EAGLE/getSpatialData#2]
Thanks for the great package, really saves time to filter and download EO data!

I think I found a small problem in the `getSentinel_query` function. I see that I always get 200 records of the returned data.frame. 
In line 74 in `getSentinel_query` function (I downloaded github version 28 May 2018),
the following lines will quit the while loop after the second batch of requests:

`if (length(query.list) != 100)
 re.query <- F`
The `query.list`  list is progressively filled with results so I believe it could be changed to:

`if (length(query.list) != row.start+100 )
 re.query <- F`

Hope this helps.
Cheers,
Francesco

PS an optional input parameter to the function, defining maximum number of returned results would also be a very nice plus, to avoid infinite number of downloaded records.

**Comment by 16EAGLE** [comment]
Thank you for using and testing getSpatialData and for investigating and pointing out the paging mistake. I fixed it according to your solution (will be referenced in NEWS).

**Comment by fpirotti** [comment]
Works great, thanks for the quick fix.
I also looked for a way  to add extra filters to the called URL, since my target is to get all Sentinel-1 data over intersection of a very small bounding box (1km x 1km) for the _months of January and December_ in the past 5 years.  Filtering  data.frame AFTER getSentinel_query would imply downloading a very large amount of data (about 500 Sentinel-1 images per year). It took my PC 2 minutes to get the answer from ESA's servers for a one year range over the 1km2 bounds. Increasing time range and/or zooming out  esponentially increases the amount of results and the time-of-retreival, making my app a bit impractical.
Filtering directly in the URL would be a solution, but ESA SciHub has two different APIs - Open Data Protocol (OData) and Open Search (Solr) and it is not possible, to my knowledge, to use a single API to filter for area intersection AND month. If I find a solution for implementing server-side filtering I will propose it. Thanks.
