### ISSUE TITLE
Potential issue with projection in display of getMODIS_preview

### ISSUE THREAD

**Issue by mtreg** [16EAGLE/getSpatialData#23]
When using getMODIS_preview the preview seems like it might not be projected appropriately. For example, when using getMODIS_preview as in Issue #22 this is how it displays: 
![incorrectprojection](https://user-images.githubusercontent.com/8225986/54227162-be1ff900-44d5-11e9-8576-603013d023a1.png)

However - when downloading the data separately, using rgdal/raster to import the data, and mapview to view the data, this is the result (and land cover types make sense when using an imagery-based baselayer): 
![correctprojection](https://user-images.githubusercontent.com/8225986/54227350-1b1baf00-44d6-11e9-9dcc-c37f80abd781.png)

Thus, it just seems like something is off when using the preview image - it looks like the getMODIS_preview function, the image actually gets stretched to the bounding box of the MODIS tile.

**Comment by 16EAGLE** [comment]
Thanks for pointing this out. Should be resolved for MODIS previews (now preview is first projected into sinusoidal, before the footprint is assigned), please reinstall. Would be nice if you could report if previewing works correctly now for your queries.

**Comment by mtreg** [comment]
The preview is now projected appropriately - thanks again!
