### ISSUE TITLE
getSentinel_data() for Sentinel-3 results in an ERROR

### ISSUE THREAD

**Issue by RemoteSensingR** [16EAGLE/getSpatialData#27]
`# Get Sentinel-3 Data`

`packages_demanded <- c("sp", "rgdal", "raster", "rgeos", "RStoolbox", "devtools", "water")`
`install.packages(packages_demanded)`
`lapply(packages_demanded, require, character.only = TRUE)`

`devtools::install_github("16eagle/getSpatialData")`
`library(getSpatialData)`

`setwd("C:/Users/UnknownUser")`
`wd <- getwd()`

`epsg4326 <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"`
`aoi_epsg4326 <- createAoi(topleft = c(-9.136454, 41.138178), bottomright = c(-7.310318, 38.707536), EPSG = 4326)`
`aoi_epsg4326 <- as(aoi_epsg4326, "SpatialPolygonsDataFrame")`
`# create AOI`

`login_CopHub("UnknownUser")`

`set_aoi(aoi_epsg4326)`

`query <- getSentinel_query(time_range = c("2017-06-17", "2017-06-19"), platform = "Sentinel-3")`

`query_filt_1 <- query[query$producttype == "SL_1_RBT___", ]`
`query_filt_2 <- query_filt_1[7:8, ]`

`getSentinel_data(records = query_filt_2, dir_out = paste0(wd, "/Data/Sentinel3"))`
`# results in following ERROR`
`# Error in !records$online : invalid argument type`

**Comment by 16EAGLE** [comment]
Thanks. Should be resolved with the latest commit!
