### ISSUE TITLE
SAFE archive downloaded without .zip extension

### ISSUE THREAD

**Issue by kadyb** [16EAGLE/getSpatialData#28]
This is probably a regression. Previously, Sentinel 2 SAFE format was downloaded normally, but now is without .zip extension and there is no possibility to unzip (you must add it manually).
```
library("getSpatialData")
login_CopHub(username = "username", password = "password")
data("aoi_data")
aoi <- aoi_data[[1]]
set_aoi(aoi)

records <- getSentinel_query(time_range = c("2019-01-01", "2019-01-30"), platform = "Sentinel-2")

datasets <- getSentinel_data(records[1, ], dir_out = "C:/scene")
datasets
[1] "C:/scene/S2A_MSIL2A_20190127T102311_N0211_R065_T32UPV_20190127T134739.SAFE"

list.files("C:/scene")
[1] "S2A_MSIL2A_20190127T102311_N0211_R065_T32UPV_20190127T134739.SAFE"
```

**Comment by 16EAGLE** [comment]
This should have been fixed ca. 4 hours ago with commit 830c63589a6bb2615c7fa95d942db8f72c0ca209  (I accidentally created this bug when support for `Sentinel-5P` and `GNSS` was added yesterday and found it today). Could you reinstall the most recent version and report me, if the issue still exist?

**Comment by 16EAGLE** [comment]
Found another issue, now it should work again

**Comment by kadyb** [comment]
It is fixed, thanks.
