### ISSUE TITLE
getMODIS_data not working due to LAADS FTP deprecation

### ISSUE THREAD

**Issue by 16EAGLE** [16EAGLE/getSpatialData#3]
Data download via FTP no longer possible due to new NASA policies: LAADS deprecation of FTP access https://ladsweb.modaps.eosdis.nasa.gov/alerts-and-issues/?id=22211.

**Comment by 16EAGLE** [comment]
fixed

**Comment by GwMo** [comment]
Hello,

_Do you know why getMODIS_names is an empty list ?_

> getMODIS_names(username = "xxxx")
list()
> product <- grep("MOD13Q1", product_names, value = T)
> product
character(0)

_And when I try to create a query, the dataset isn't available. Is it the name of the product which doesn't work ?_

> query = getMODIS_query(time_range = c("2018-01-01","2017-10-25"), name = "MOD11A1", aoi = coordinates)
Searching USGS EarthExplorer for available products...
Error: Invalid query. This dataset seems to be not available for the specified time range.

Thank you.

**Comment by 16EAGLE** [comment]
Please see my response in issue #8.
