### ISSUE TITLE
getSentinel_query is producing an error in doc_parse_raw with Sentinel 3

### ISSUE THREAD

**Issue by MilanFischer** [16EAGLE/getSpatialData#35]
Hello,
I am trying to use the function getSentinel_query exactly following the example at the main page with only difference that I am using Sentinel 3 platform.
I am receiving the following error message:

```r
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  xmlParseEntityRef: no name [68]
In addition: Warning messages:
1: In doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  :
  Entity 'nbsp' not defined [27]
2: In doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  :
  Entity 'nbsp' not defined [27]
```
It seems that the problem  arises in
```r
as_xml_document(content(query, 
            as = "text"))
```
which is in getSentinel_query.R code. If ```'&nbsp;'``` is replaced by ```'&#160;'``` using gsub function in this code, the warning disappears, however, the error in doc_parse_raw remains.

I am using getSpatialData_0.0.4 with R 3.6.0 on Windows 10.

Please, do you have any suggestions?

Best,
Milan

**Comment by 16EAGLE** [comment]
Hello, thanks for reporting this bug. I'm looking into it. Could you please provide the exact call to `getSentinel_query` that resulted in the error? That makes it easier for me to fully track it down. Thanks in advance

**Comment by MilanFischer** [comment]
Hello, thanks for the prompt response.
```
## Load package
library(getSpatialData)

## Define an AOI (either matrix, sf or sp object)
data("aoi_data") # example aoi

aoi <- aoi_data[[1]] # AOI as sf object

## Set AOI for this session
set_aoi(aoi)

## Set login credentials and archive directory
login_CopHub(username = "my_user_name") 
set_archive(paste(getwd(),'/Test',sep=''))

## Use getSentinel_query to search for data (using the session AOI)
records <- getSentinel_query(time_range = c("2018-08-01", "2018-08-30"), platform = "Sentinel-3") #or "Sentinel-1", "Sentinel-2" or "Sentinel-3"
```

Please, let me know if you need more details.

Best,
Milan

**Comment by 16EAGLE** [comment]
Thanks, the issue should be resolved with the latest commit. Reason was the decommissioning of the Copernicus Sentinel-3 PreOps Hub on June 19, 2019 (https://scihub.copernicus.eu/news/News00550). Sentinel-3 queries thus were redirected falsely, but now go directly via `dhus` as Sentinel-1 and -2. 

Please reinstall `getSpatialData` from `master`. Could you also please confirm that the code above now works for you without throwing errors on your end? Thanks for catching this!

**Comment by MilanFischer** [comment]
Thanks a lot for very quick  fix!
I just installed the new version and the `getSentinel_query` works without any problem for Sentinel 3 now.

Best,
Milan
