### ISSUE TITLE
Installation failure due to deprecation of `devtools::system_check`

### ISSUE THREAD

**Issue by lbusett** [16EAGLE/getSpatialData#37]
Hi, 
   
 after updating packages today, I noticed that installation of `getSpatialData` fails due to deprecation of `devtools::system_check`

``` r
Error: object ‘system_check’ is not exported by 'namespace:devtools'
Execution halted
ERROR: lazy loading failed for package ‘getSpatialData’
* removing ‘/home/lb/R/x86_64-pc-linux-gnu-library/3.6/getSpatialData’
* restoring previous ‘/home/lb/R/x86_64-pc-linux-gnu-library/3.6/getSpatialData’
Error: Failed to install 'testbf' from GitHub:
  Failed to install 'getSpatialData' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpSdO1QS/file1bb20b7eddd/getSpatialData_0.0.4.tar.gz’ had non-zero exit status
```

(see https://github.com/r-lib/devtools/blob/c76ed73744a5ce9dd0bb824e63f5444c4f32a370/NEWS.md)

The function should be probably replaced by a call to 

```r
processx::process$new
```

I will draft a PR later on today (though AFAICS the function is never used within the package, so it seems it could be safely removed)

**Comment by 16EAGLE** [comment]
Thanks for the PR. You're right, `check.cmd` is currently not in use. If it stays this way, I'll remove it before the initial on CRAN (hopefully soon).
