### ISSUE TITLE
Downloading Stop

### ISSUE THREAD

**Issue by Himesh91** [16EAGLE/getSpatialData#41]
Code is running all ok .
When i start download using command line  **datasets <- getSentinel_data(records = records_filtered[1,])**

Download starts but its stops at any percentage such as 65%,17%,25% but never completed to 100%.Earlier it used to be completed to 100% but now it seems to fail.Tried network change still no solution

Any solution is appreciated..
![issue](https://user-images.githubusercontent.com/53744182/62453026-14e0e480-b78f-11e9-83b2-fe2e184a6c99.png)

**Comment by 16EAGLE** [comment]
Could you provide a reproducible code example of your download request? Unfortunately, I am not aware of what causes this issue and cannot attempt to find its cause without reproducing your request.

**Comment by Himesh91** [comment]
Now it is working properly issue was on the copernicus side.Thanx for the concern.
