### ISSUE TITLE
login_USGS on RStudio Server running in Ubuntu 18.04? 

### ISSUE THREAD

**Issue by Matiasedguzman** [16EAGLE/getSpatialData#48]
Hi,
I'm trying to use login_USGS on RStudio Server but the console show me the next error: 
'Error: Login failed. Please retry later or call services_avail() to check if USGS services are currently unavailable.'
 Is this an error from the USGS server or login_USGS not working in this version of Ubuntu?

All the best and thanks,
Matias

**Comment by 16EAGLE** [comment]
Hi Matias,

when have you installed the version of `getSpatialData` currently running on your server? `getSpatialData` has been updated 2 day ago with commit 2525bf2. This should fix the USGS login issue. Please let me know if you keep facing this error with the most recent version.

Best,
Jakob

**Comment by Matiasedguzman** [comment]
Jakob,

the problem was fixed. Thank you very much!

Matías
