### ISSUE TITLE
Can't seem to get the install to work

### ISSUE THREAD

**Issue by RussellGrayxd** [16EAGLE/getSpatialData#49]
The install says something along the lines of "no GDAL installed" and then provides a list of gdal providers, though it doesn't say where the file should be placed for the install to work, nor does it mention on the intstall page of this Github repository that it needs to be installed as a requirment to begin with. 

Please help!

Thanks in advance,

-Russell Gray

**Comment by 16EAGLE** [comment]
Hi Russell, getSpatialData itself does not link to GDAL, however it dependencies (`raster`, `sf`) do. You may want to use this guide on how to install GDAL: https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL
