### ISSUE TITLE
prepSentinel extraction fails on Windows for deep folder structures

### ISSUE THREAD

**Issue by 16EAGLE** [16EAGLE/getSpatialData#5]
prepSentinel extraction fails on Windows for directories with large path lengths. Same issue occurs for renaming folders in such directories.

**Comment by eartherin** [comment]
I am running into this problem. Do you have a suggestion for a fix, beyond extracting manually using Zip7 or something similar?

**Comment by 16EAGLE** [comment]
Until there is a long-term solution, one workaround I could suggest is mounting the folder containing your zip files as a drive to shorten the overall path lengths (see https://superuser.com/a/109408 to do this), index the drive using `list.files()` with `full.names = TRUE` and supply the returned list to `prepSentinel`. I have tested this some months ago when I discovered that this issue is related to the lengths of the overall paths of files inside the zip archives due to the long folder names contained.

**Comment by PabloCSZ** [comment]
Hi, 
I think I am having similar problems related with this issue. The prepSentinel function is able to extract, sort, and stack the bands. However, the result is only a prep_data folder with empty folders related to the tiles I choosed. 
I already did the all the above.

**Comment by UK85** [comment]
Hi,
I get the same warnings() as PabloCSZ. Running getSpatialData on a Windows machine and the suggested fix does not help. Any ideas?

Also, when loading the getSpatialData package I get the error message from gdalinfo.exe "ogdi.dll missing". How can I fix this? 

```
In system(cmd, intern = TRUE) :
  Ausführung von Kommando '"C:\Program Files\QGIS 3.4\bin\gdalbuildvrt.exe" -resolution "highest" -separate  "C:\Users\XXX\Documents\GIS\RemoteSensing\rawdata\/prep_data/SENTINEL//L2A_T32UPU_A009600_20170424T101120/S2A_MSIL2A_20170424T101031_N0204_R022_T32UPU_20170424T101120_10m_aux.vrt" "M:\S2A_MSIL2A_20170424T101031_N0204_R022_T32UPU_20170424T101120/L2A_T32UPU_A009600_20170424T101120/S2A_MSIL2A_20170424T101031_N0204_R022_T32UPU_20170424T101120.SAFE/GRANULE/L2A_T32UPU_A009600_20170424T101120/IMG_DATA/R10m/L2A_T32UPU_20170424T101031_AOT_10m.jp2" "M:\S2A_MSIL2A_20170424T101031_N0204_R022_T32UPU_20170424T101120/L2A_T32UPU_A009600_20170424T101120/S2A_MSIL2A_20170424T101031_N0204_R022_T32UPU_20170424T101120.SAFE/GRANULE/L2A_T32UPU_A009600_20170424T101120/IMG_DATA/R10m/L2A_T32UPU_20170424T101031_TCI_10m.jp2" "M:\S2A_MSIL2A_20170424T101031_N0204_R022_T32UPU_20170424T101120/L2A_T32UPU_A009600_20170424T101120/S2A_MSIL2A_20170424T101031_N0204_R022_T32UPU_20170424T101120.SAFE/GRANULE/L2A_T32UPU_A009600_20170424T101120/IMG_DATA/R10m/L2A_T32UPU_20170424T101031_WVP_10m.jp2"' ergab Status 1
```

**Comment by 16EAGLE** [comment]
prepSentinel has been deprecated since I did not find the time to maintain it and implement support for all archive structures, differing product- and level-wise. If someone wants to work on that end of the package, please let us know!
