### ISSUE TITLE
prepSentinel function  - Error in gdal_chooseInstallation(hasDrivers = of)

### ISSUE THREAD

**Issue by josemsilva** [16EAGLE/getSpatialData#50]
I'm trying to download sentinel 2 images with the package, and it works perfect until the getSentinel_data function. However, when executing the prepSentinel function,

**datasets_prep <- prepSentinel(datasets, format = "tiff")**

I get the following error:

**Error in gdal_chooseInstallation(hasDrivers = of) : No installations match. Además: Warning messages: 1: In system(cmd, intern = TRUE) : comando ejecutado '"C:\Program Files\QGIS 3.10\bin\gdalbuildvrt.exe" -resolution "highest" -separate**

Thank you very much in advance

**Comment by 16EAGLE** [comment]
prepSentinel has been deprecated since I did not find the time to maintain it and implement support for all archive structures, differing product- and level-wise. If someone wants to work on that end of the package, please let us know!
