### ISSUE TITLE
gdal error

### ISSUE THREAD

**Issue by khalilT** [16EAGLE/getSpatialData#52]
Hi,
I can't load the `getSpatialData` anymore because of a gdal error:

the error message is:

`probably broken install of gdal at 'C:/Qgis/apps/gdal2/bin/'
Error: package or namespace load failed for ‘getSpatialData’:
 .onLoad failed in loadNamespace() for 'getSpatialData', details:
  call: strsplit(sapply(drivers, function(x) {
  error: non-character argument
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  running command '"C:\Qgis\apps\gdal2\bin\gdalinfo.exe" --version' had status 309
2: In FUN(X[[i]], ...) :
  running command '"C:/Qgis/apps/gdal2/bin//gdalinfo" --formats' had status 309`

anybody has an idea how to fix this?

Thanks !

**Comment by daluna1** [comment]
I have the same problem. Did you solved it?

**Comment by 16EAGLE** [comment]
Sorry for the late reply. It tells that your GDAL installation might be broken. `getSpatialData` itself does not link to GDAL, however it dependencies (raster, sf) do. It may be worth considering reinstallating GDAL or installing it independently from QGIS. You may want to use this guide on how to install GDAL: https://github.com/domlysz/BlenderGIS/wiki/How-to-install-GDAL
