### ISSUE TITLE
Sentinel 5p "Error: Could not process request: is.character(user) is not TRUE"

### ISSUE THREAD

**Issue by SFrav** [16EAGLE/getSpatialData#54]
I'm getting the following error on R 3.6.1 using R studio 1.1.456: Error: Could not process request: is.character(user) is not TRUE

Here's the code used:
`getSentinel_query(platform = "Sentinel-5p", aoi = EA_shp, time_range = c("2020-01-01", "2020-02-28"), username = "s5pguest", password = "s5pguest")`

**Comment by SFrav** [comment]
The issue was caused by using a lower case 'p' in the platform variable. The same may happen if any platform is entered as lowercase, right? 

Perhaps generalise line 125 for all platforms and combinations. Something like this on line 122 of getSentinel_query.R:
```
platform <- gsub("^s", "S", platform)
platform <- gsub("([A-Za-z])$", "", platform)
```

**Comment by omidnabavi** [comment]
Hi, 
Could I ask you how you logged in sentinel 5p? I use general function for the open hub but it cannot search sentinel 5p.
This is what I used:
`login_CopHub(username = "s5pguest", password = "noreply@noa.gr")
`Best regards,
Omid.

**Comment by SFrav** [comment]
The login for sentinel 5p is:
`username = "s5pguest", password = "s5pguest"`

**Comment by omidnabavi** [comment]
It does not work:
login_CopHub(username = "s5pguest", password = "s5pguest")
Error: Login failed. Please retry later or call services_avail() to check if ESA Copernicus services are currently unavailable.

**Comment by omidnabavi** [comment]
Thanks. I tried my user pass created for the open hub (not for sentinel 5p hub). Now it is working.

**Comment by 16EAGLE** [comment]
Hi, the correct credential selection depending on the requested product should now work again, meaning that you now would not have to define S5-pre-ops credentials manually and only your Copernicus Open Access Hub credentials are required.
