### ISSUE TITLE
Sentinel-1 - prepSentinel - Error: Selected tiles are not contained within dataset.

### ISSUE THREAD

**Issue by RobertSellers** [16EAGLE/getSpatialData#55]
Hi,

This question I believe was also raised here.

https://stackoverflow.com/questions/58930318/don-work-prepsentinel-with-sentinel-1-data

Do you have a solution or explanation to this? Is the data now repackaged and this function no longer current for sentinel-1?

**Comment by max-ionov** [comment]
It looks like the contents of the downloaded archives differ from what is expected by the function.
As far as I can see, the problem starts here: https://github.com/16EAGLE/getSpatialData/blob/2525bf25ae255ae0fa534f1b9b8e07064884a8ea/R/prepSentinel.R#L94
There are no `*.jp2` files in the unzipped archives from Sentinel-1, GRD (nor there are `IMG_DATA*` files).

I am not familiar with the structure of these products. Is this a problem of Sentinel-1 output being different from Sentinel-2 or did they change the contents?

**Comment by 16EAGLE** [comment]
`prepSentinel` has been deprecated since I did not find the time to maintain it and implement support for all archive structures, differing product- and level-wise.
