### ISSUE TITLE
Error view_previews() and calc_cloudcov()

### ISSUE THREAD

**Issue by qxu6** [16EAGLE/getSpatialData#65]
I got two problems when I tried to run the code from this tutorial(I only used data from USGS): https://github.com/16EAGLE/getSpatialData/blob/master/README.md

(1) When I run view_previews(records), got the error 
"Error in leafem::addHomeButton(map = map, ext = ext, layer.name = layer.name,  : 
  unused argument (layer.name = layer.name)". 

(2) When I run calc_cloudcov(records), got the error
[Aoi cloudcov calc 1/1] Processing: LC08_L1TP_194025_20200516_20200527_01_T1
Error in st_write.sf(records, dsn = file, append = append, quiet = TRUE) : 
  unrecognized argument(s) append 

Error: Failed to write file: mypath/LC08_L1TP_194025_20200516_20200527_01_T1.geojson

Many thanks if anyone could help with these two problems.

**Comment by hfisser** [comment]
Hi,

could you please share a code snippet? Then we can understand the used arguments. Also, the version number of the sf package would help. Thanks

**Comment by qxu6** [comment]
Hi @hfisser,

Thank you so much for your quick response!

Here is my code:

library(getSpatialData)
data("aoi_data")
set_archive("/path/to/my/archive/directory/")
set_aoi(aoi_data[[1]])
login_USGS(username = "myusername")
records <- get_records(time_range = c("2020-05-15", "2020-05-30"),
                       products =  "LANDSAT_8_C1")
records <- records[records$level == "sr",]      #6 obs of 22 variables
unique(records$record_id)
#[1] "LC08_L1TP_194025_20200516_20200527_01_T1" "LC08_L1TP_194026_20200516_20200527_01_T1" "LC08_L1GT_195025_20200523_20200607_01_T2"
#[4] "LC08_L1GT_195026_20200523_20200607_01_T2" "LC08_L1TP_193025_20200525_20200608_01_T1" "LC08_L1TP_193026_20200525_20200608_01_T1"

records <- get_previews(records)
view_previews(records)
#Composing preview map...
#Error in leafem::addHomeButton(map = map, ext = ext, layer.name = layer.name,  : 
#                                 unused argument (layer.name = layer.name)
plot_previews(records)
records <- calc_cloudcov(records[,]) 
#---------------------------------------------------------------------------------
#Processing 6 records
#---------------------------------------------------------------------------------
  
#  [Aoi cloudcov calc 1/6] Processing: LC08_L1TP_194025_20200516_20200527_01_T1
#Error in st_write.sf(records, dsn = file, append = append, quiet = TRUE) : 
#  unrecognized argument(s) append 

#Error: Failed to write file: /my/path/LC08_L1TP_194025_20200516_20200527_01_T1.geojson
#this created a new folder "_cloud_masks" and there was one file in this folder "LC08_L1TP_194025_20200516_20200527_01_T1_cloud_mask.tif"

A few more details about the versions:
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.5

**Comment by qxu6** [comment]
Thanks @hfisser . These two problems solved when I updated R, R studio and sf to the latest version!

**Comment by hfisser** [comment]
Great to hear that!
