### ISSUE TITLE
Maybe USGS server error?

### ISSUE THREAD

**Issue by fishish1** [16EAGLE/getSpatialData#66]
Hi, I'm having trouble downloading Landsat data.  I've used this package for Sentinel 2 and love it! I successfully log in using my USGS Account and getLandsat_records.

`records_Landsat <- getLandsat_records(time_range = c(start_records, end_records), products = "LANDSAT_8_C1")`

However, when I try to use these records to access a dataset, 

`  datasets_Landsat <- getLandsat_data(records = records_Landsat_filtered)`

I get this error:

`Error in .get(paste0(getOption("gSD.api")$espa, "/order/", x), getOption("gSD.usgs_user"),  : 
  Internal Server Error (HTTP 500). Failed to process request.`

It seems like a strange error so I'm likely doing something wrong... but I can't figure it out.

**Comment by LaurentSmeets** [comment]
I am having the exact same problem, I am able to download Sentinel products though.

**Comment by 16EAGLE** [comment]
Hi, thanks for reporting the issue. Could you please provide a reproducible example with AOI and time range that produces the error so that I can test this on my end? Thanks!

**Comment by 16EAGLE** [comment]
I could not reproduce the issue you are describing, neither for direct downloads with `level=="l1"` via `AWS` nor for ordered downloads, e.g. with `level=="sr"` (see examples below). Are you using the most recent `getSpatialData` version, `0.1.0`? If so I would be very interested in a rproducible example as below that produces the error.

Query and download of `LANDSAT_8_C1` `l1` data:

```R
library(getSpatialData)

#login
login_USGS(username = "myuser")
login_earthdata(username = "myuser")

# session settings
set_archive(dir_archive = "path/to/archive")
set_aoi(aoi_data[[1]])

# query
records <- get_records(time_range = c("2018-05-15", "2018-05-25"),
                       products = "LANDSAT_8_C1") 
records <- records[records$level == "l1",] # filter level 1 records
records <- check_availability(records) # check availability
records <- get_data(records) # download
# > Receiving MD5 checksums...
# > Assembling dataset URLs...
# > [Dataset 1/4 | File 1/38] Downloading dataset 'LC08_L1TP_195025_20180518_20180604_01_T1 (l1)'
# > to '/home/xxxxx/xxxxx/tmp/gSD_datasets/LANDSAT_8_C1//LC08_L1TP_195025_20180518_20180604_01_T1'
# > |================================================================| 100%
```

Query, download and order of `LANDSAT_8_C1` `sr` data: 

```R
records <- get_records(time_range = c("2018-05-15", "2018-05-25"),
                       products = "LANDSAT_8_C1") 
records <- records[records$level == "sr",] # filter surface reflectance records
records <- check_availability(records) # check availability
records <- order_data(records) # order records
records <- get_data(records) # download records when order is available
# > Receiving MD5 checksums...
# > Assembling dataset URLs...
# > [Dataset 1/4 | File 1/1] Downloading dataset 'LC08_L1TP_195025_20180518_20180604_01_T1 (sr)' to 
# > '/home/xxxxx/xxxxx/tmp/gSD_datasets/LANDSAT_8_C1//LC08_L1TP_195025_20180518_20180604_01_T1_LEVEL_sr.tar.gz'...
# > |================================================================| 100%
```

(Same results with `getLandsat_data()` as this is simply an alias for `get_data()`)

**Comment by LaurentSmeets** [comment]
Ok, I figured maybe my login credentials for the Earth Data API are faulty. (although I can login here: https://search.earthdata.nasa.gov/search with the same username and password). 

```
library(getSpatialData)
login_USGS(username = "My_username", password = "My_pw")
```
Login successfull. USGS ERS credentials have been saved for the current session.
```
login_earthdata(username = "My_username2", password = "My_pw2", verbose = F)
```
Error: Login failed. Please retry later or call services() to check if LAADS is currently unavailable.


*I did, it was available. so now I think the problem might be with my login credentials. would that make sense? I can just download the tiles I want manually from USGS without the Earth Data account.*

```
set_archive("./pictures2/")
set_aoi(aoi_data[[1]])
records <- get_records(time_range = c("2018-05-15", "2018-05-25"),
                       products = "LANDSAT_8_C1") 
```
Searching records for product name 'LANDSAT_8_C1'...
Reading meta data of search results from USGS EarthExplorer...
Recieving available product levels from USGS-EROS ESPA...

```
> records

```
```
Simple feature collection with 4 features and 21 fields
geometry type:  POLYGON
dimension:      XY
bbox:           xmin: 6.8963 ymin: 47.78422 xmax: 13.84065 ymax: 51.34911
geographic CRS: WGS 84
   product_group      product                                record_id
2        Landsat LANDSAT_8_C1 LC08_L1TP_195025_20180518_20180604_01_T1
18       Landsat LANDSAT_8_C1 LC08_L1TP_195026_20180518_20180604_01_T1
34       Landsat LANDSAT_8_C1 LC08_L1TP_193025_20180520_20180605_01_T1
50       Landsat LANDSAT_8_C1 LC08_L1TP_193026_20180520_20180605_01_T1
               entity_id
2  LC81950252018138LGN00
18 LC81950262018138LGN00
34 LC81930252018140LGN00
50 LC81930262018140LGN00
                                                                                                summary
2  Entity ID: LC08_L1TP_195025_20180518_20180604_01_T1, Acquisition Date: 18-MAY-18, Path: 195, Row: 25
18 Entity ID: LC08_L1TP_195026_20180518_20180604_01_T1, Acquisition Date: 18-MAY-18, Path: 195, Row: 26
34 Entity ID: LC08_L1TP_193025_20180520_20180605_01_T1, Acquisition Date: 20-MAY-18, Path: 193, Row: 25
50 Entity ID: LC08_L1TP_193026_20180520_20180605_01_T1, Acquisition Date: 20-MAY-18, Path: 193, Row: 26
````
*So far, so good*
```
records <- records[records$level == "l1",] # filter level 1 records
records <- check_availability(records) # check availability
```

Checking availability for Landsat records...
Investigating matching ESPA orders in the past...
Error in .get(paste0(getOption("gSD.api")$espa, "/order/", x), getOption("gSD.usgs_user"),  : 
  Internal Server Error (HTTP 500). Failed to process request.


```
sessionInfo()
```

```
R version 4.0.1 (2020-06-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252   
[3] LC_MONETARY=Dutch_Netherlands.1252 LC_NUMERIC=C                      
[5] LC_TIME=Dutch_Netherlands.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] getSpatialData_0.1.0 raster_3.3-7         sp_1.4-2            

loaded via a namespace (and not attached):
  [1] nlme_3.1-148         sf_0.9-4             satellite_1.0.2     
  [4] lubridate_1.7.9      doParallel_1.0.15    webshot_0.5.2       
  [7] httr_1.4.1           mapview_2.7.8        tools_4.0.1         
 [10] rgdal_1.5-12         R6_2.4.1             rpart_4.1-15        
 [13] KernSmooth_2.23-17   rgeos_0.5-3          DBI_1.1.0           
 [16] colorspace_1.4-1     nnet_7.3-14          withr_2.2.0         
 [19] tidyselect_1.1.0     leaflet_2.0.3        curl_4.3            
 [22] compiler_4.0.1       leafem_0.1.1         cli_2.0.2           
 [25] xml2_1.3.2           scales_1.1.1         classInt_0.4-3      
 [28] pbapply_1.4-2        stringr_1.4.0        digest_0.6.25       
 [31] R.utils_2.9.2        base64enc_0.1-3      pkgconfig_2.0.3     
 [34] htmltools_0.5.0      fastmap_1.0.1        htmlwidgets_1.5.1   
 [37] rlang_0.4.6          rstudioapi_0.11      shiny_1.5.0         
 [40] generics_0.0.2       jsonlite_1.7.0       crosstalk_1.1.0.1   
 [43] dplyr_1.0.0          ModelMetrics_1.2.2.2 R.oo_1.23.0         
 [46] magrittr_1.5         geosphere_1.5-10     patchwork_1.0.1     
 [49] Matrix_1.2-18        Rcpp_1.0.4.6         munsell_0.5.0       
 [52] fansi_0.4.1          lifecycle_0.2.0      R.methodsS3_1.8.0   
 [55] stringi_1.4.6        pROC_1.16.2          MASS_7.3-51.6       
 [58] plyr_1.8.6           recipes_0.1.13       grid_4.0.1          
 [61] ggrepel_0.8.2        parallel_4.0.1       promises_1.1.1      
 [64] crayon_1.3.4         lattice_0.20-41      splines_4.0.1       
 [67] pillar_1.4.4         gdalUtils_2.0.3.2    reshape2_1.4.4      
 [70] codetools_0.2-16     stats4_4.0.1         XML_3.99-0.3        
 [73] glue_1.4.1           getPass_0.2-2        data.table_1.12.8   
 [76] vctrs_0.3.1          png_0.1-7            httpuv_1.5.4        
 [79] foreach_1.5.0        gtable_0.3.0         purrr_0.3.4         
 [82] assertthat_0.2.1     ggplot2_3.3.2        gower_0.2.2         
 [85] mime_0.9             prodlim_2019.11.13   lwgeom_0.2-5        
 [88] xtable_1.8-4         e1071_1.7-3          later_1.1.0.1       
 [91] class_7.3-17         survival_3.1-12      RStoolbox_0.2.6     
 [94] viridisLite_0.3.0    timeDate_3043.102    tibble_3.0.1        
 [97] iterators_1.0.12     units_0.6-7          lava_1.6.7          
[100] mapedit_0.6.0        ellipsis_0.3.1       caret_6.0-86        
[103] ipred_0.9-9  
```

**Comment by 16EAGLE** [comment]
Thanks for the infos.

1. Actually, it was my mistake to include the `login_earthdata()` function in my example above (I edited it and removed it): For this query, only a USGS ERS account is needed, (earthdata login is only required for MODIS downloads). The issue that you cannot login to your earthdata account should not be related to the `check_availability()` error you see (side note regarding the login issue: have you tried if you can login at https://urs.earthdata.nasa.gov/ ? Maybe you could try to create a new account and see if the problem persists. If so please open another issue).

2. `check_availability()` should not check for ESPA orders if level is L1. I fixed this with the latest commit. Please reinstall `getSpatialData` from GitHub and run the level-1 example again.

3. Still, the error shown is worth investigating since the expected result would have been a response from ESPA containing all past orders by your account that are then compared to the requested record ids. After reinstalling `getSpatialData`, could you run the `sr` example from above and let me know if you get the same error or not?

Thanks for helping me find these bugs!

**Comment by LaurentSmeets** [comment]
Thanks for the quick reply. I am a big fan of the proposed pipeline, workflow proposed by this package.  Yes I can login on  https://urs.earthdata.nasa.gov/ (i have not tried making a new account yet, MODIS are not really of interest now to me). The code now works for the level-1, but I get the same error if I try any other level.

```
remove.packages("getSpatialData")
devtools::install_github("16EAGLE/getSpatialData")
library("getSpatialData")
login_USGS(username = "My_username", password = "My_pw")
# session settings
set_archive("./pictures2/")
set_aoi(aoi_data[[1]])

# query
records <- get_records(time_range = c("2018-05-15", "2018-05-25"),
                       products = "LANDSAT_8_C1") 
records_l1 <- records[records$level == "l1",] # filter level 1 records
records_l1 <- check_availability(records_l1) # check availability
```

```
Checking availability for Landsat records...
4/4 records are currently available for download (this includes past completed orders that are still available for download).
Columns added to records: 'download_available', 'order_status', 'order_id', 'ordered'
```
This worked. However:
```
> records_sr <- records[records$level == "sr",] # filter level sr records
> records_sr <- check_availability(records_sr) # check availability
```

```
Checking availability for Landsat records...
Investigating matching ESPA orders in the past...
Error in .get(paste0(getOption("gSD.api")$espa, "/order/", x), getOption("gSD.usgs_user"),  : 
  Internal Server Error (HTTP 500). Failed to process request.
```

**Comment by 16EAGLE** [comment]
Glad you like the workflow!

Could you please open `https://espa.cr.usgs.gov/api/v1//list-orders` in your browser and login when asked with your ERS credentials? Do you see order IDs of past orders? If not, have you already used ESPA before or never with this account? 

If you see order IDs, could you copy one of them (like `espa-abcd@efg.xy-12345678-081833-879`) and open it pastedpasted with this `https://espa.cr.usgs.gov/api/v1//order/` in your browser? Example: `https://espa.cr.usgs.gov/api/v1//order/espa-abcd@efg.xy-12345678-081833-879`. This will resemble the kind of API request that your error above comes from. Do you get a response or does this also result in a 500 server error?

Hope this will shed some light on this.

**Comment by LaurentSmeets** [comment]
No I have not used ESPA before with this account (just downloaded directly from the USGS Earth Explorer before).  If I follow that link, I just get an empty page with a `[]` in the topleft corner. If I paste https://espa.cr.usgs.gov/api/v1//order/espa-abcd@efg.xy-12345678-081833-879 to the page, I get this error message:  `{"message": "Internal Server Error"}`

**Comment by fishish1** [comment]
I have reproduced @LaurentSmeets results with my credentials, following these steps.

**Comment by 16EAGLE** [comment]
Thanks, I think I found the cause of the issue – a parsing problem for ESPA order list responses that are empty which is always the case with accounts that have not been used for orders before. Therefore another request: Please reinstall `getSpatialData` and retry the `sr` example from above, in particular `check_availability()` and then if that succeeds `order_data()`.

With `order_data()`, you can use the argument `wait_to_complete = TRUE` to keep the function running and monitoring ESPA until the order is ready for download, like this:

```R
records <- check_availability(records)
records <- order_data(records, wait_to_complete = T)
records <- get_data(records)
```

**Comment by LaurentSmeets** [comment]
This seems to have fixed it for me. It worked. Thanks.

**Comment by fishish1** [comment]
Thanks all!
