### ISSUE TITLE
Login Théia

### ISSUE THREAD

**Issue by RozoC** [16EAGLE/getSpatialData#7]
Dear Mr, 

First, many thanks for your work on this package. I used it for S-2 and S-1 and it's work well. 

Then, i have to download sentinel images from the web site "http://www.theia-land.fr/" for my work. 
So my question is, is it possible to download sentinel images from another site, not Copernicus but  theia and can i do it?

Thanks for your answer.

Best regard, 

C. ROZO

**Comment by 16EAGLE** [comment]
Dear Mr. Rozo,

thank you. Unfortunately, this is currently not possibility using `getSpatialData`. I have no knowledge about an R tool for accessing Theia data. However, please be referred to this Python tool that allows to access various sensor data from Theia Land: https://github.com/olivierhagolle/theia_download

Best regards
