### ISSUE TITLE
view_records() returns Error  "formal argument "fill" matched by multiple actual arguments"

### ISSUE THREAD

**Issue by priyapatel1** [16EAGLE/getSpatialData#80]
Hi,

I recently had an issue with view_aoi() function, and I was able to fix is by removing the fill=f call in the mapview function. However, I'm trying to use the view_records() function and I'm getting a similar error. I can't fix it using the same methods. I'm following the example on the getspatialdata() homepage.

Here is the code:
```
setwd("XXXX")

library(getSpatialData)
data("aoi_data")
library(mapview)

set_archive("XXXX")
library(httr)
set_aoi(aoi_data[[1]])

mapview::mapview(aoi_data[[1]],
                 layer.name = "AOI",
                 label = "AOI",
                 lwd = 6,
                 color = "Blue",
                 legend = F,
                 homebutton = F)

login_CopHub(username = "XXX")

services()
get_products()

records <- get_records(time_range = c("2020-05-15", "2020-05-30"),
                       products = c("Sentinel-5P"))

records <- records[records$level == "Level-2" | records$producttypedescription == "Nitrogen Dioxide",]

view_records(records)
```
Here is the error: 
`Error in leafem::addFgb(map = m, file = fl, radius = cex, weight = lwd,  : 
  formal argument "fill" matched by multiple actual arguments`

Can someone give me a solution to this problem?

Thanks!

**Comment by Muesgen** [comment]
Hi I saw your issue by chance and tested it.  it worked for me. I would say it is an error of the leafem package.

**Comment by priyapatel1** [comment]
@Muesgen The error given already confirmed that it's within the leafem package...

I just don't know how to address it.

**Comment by Muesgen** [comment]
@priyapatel1 

https://github.com/r-spatial/leafem

**Comment by joekroese** [comment]
Hi @priyapatel1! I was having this issue too. Same as the issue with `view_aoi()` in https://github.com/16EAGLE/getSpatialData/issues/77, this error is also from the `fill = F` parameter in the `mapview` call.

I've made a pull request that fixes both issues.

**Comment by priyapatel1** [comment]
@joekroese Really new to R - how do I use/access this pull request? Do I download the package again?

**Comment by 16EAGLE** [comment]
Thank you for reporting this issue and for your patience. Should be fixed now.
